#setting context path
server.servlet.context-path=/api

#add secret keys
spring.config.import=optional:classpath:secretkey.properties

#jwt token - custom name (must be at least 32 characters)
jwt.secret=${jwt_token}


#imgbb - API key
imgbb.apikey=${imgbb_apikey}



app.domain.frontend=${app_domain_fe}
app.domain.backend=${app_domain_be}


# Email server settings (Gmail)‰
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mail_username}
spring.mail.password=${mail_password}

# Enable SMTP authentication and TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true