#add secret keys
spring.config.import=optional:classpath:secretkey.properties

spring.datasource.url=jdbc:mysql://localhost:3306/backendDB?useSSL=false&serverTimezone=Asia/Taipei
spring.datasource.username=${datasource_username}
spring.datasource.password=${datasource_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver